<Project Sdk="Aspire.AppHost.Sdk/13.2.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9ecb4a87-3d8b-4e25-a09e-f445b9908efb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.2.1-preview.1.26180.6" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.2.1" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.2.1" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.2.1" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CorpusLegis.API\CorpusLegis.API.csproj" />
    <ProjectReference Include="..\CorpusLegis.EscrutinioWorker\CorpusLegis.EscrutinioWorker.csproj" />
    <ProjectReference Include="..\CorpusLegis.PdfWorker\CorpusLegis.PdfWorker.csproj" />
    <ProjectReference Include="..\CorpusLegis.Reputatio\CorpusLegis.Reputatio.csproj" />
    <ProjectReference Include="..\CorpusLegis.Web\CorpusLegis.Web.csproj" />
  </ItemGroup>

</Project>
