<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9ecb4a87-3d8b-4e25-a09e-f445b9908efb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CorpusLegis.API\CorpusLegis.API.csproj" />
    <ProjectReference Include="..\CorpusLegis.PdfWorker\CorpusLegis.PdfWorker.csproj" />
    <ProjectReference Include="..\CorpusLegis.Web\CorpusLegis.Web.csproj" />
  </ItemGroup>

</Project>
