@CorpusLegis.API_HostAddress = http://localhost:5208

###

GET {{CorpusLegis.API_HostAddress}}/rogatio
Accept: application/json

###

GET {{CorpusLegis.API_HostAddress}}/rogatio/744f0423-05fb-4ad5-a2c8-212973c960c0
Accept: application/json

###

POST {{CorpusLegis.API_HostAddress}}/rogatio
Content-type: application/json

{
  "title": "Amarse",
  "content": "Juntos somos",
  "status": "draft"
}

###

PUT {{CorpusLegis.API_HostAddress}}/rogatio/744f0423-05fb-4ad5-a2c8-212973c960c0
Content-type: application/json

{
  "title": "Se amen",
  "content": "Son juntos",
  "status": "Draft"
}

###

DELETE {{CorpusLegis.API_HostAddress}}/rogatio/744f0423-05fb-4ad5-a2c8-212973c960c0

###