@CorpusLegis.API_HostAddress = http://localhost:5208

###

GET {{CorpusLegis.API_HostAddress}}/rogatio
Accept: application/json

###

GET {{CorpusLegis.API_HostAddress}}/rogatio/7a3650b9-2fa1-43fe-a01c-df16647a8ade
Accept: application/json

###

POST {{CorpusLegis.API_HostAddress}}/rogatio
Content-type: application/json

{
  "title": "Amarse",
  "content": "Juntos somos",
  "status": "draft"
}

###

PUT {{CorpusLegis.API_HostAddress}}/rogatio/7a3650b9-2fa1-43fe-a01c-df16647a8ade
Content-type: application/json

{
  "title": "Se amen",
  "content": "Son juntos",
  "status": "Draft"
}

###

DELETE {{CorpusLegis.API_HostAddress}}/rogatio/7a3650b9-2fa1-43fe-a01c-df16647a8ade

###