@CorpusLegis.API_HostAddress = http://localhost:5208
@RogatioId = 501f8ef7-128f-4e9f-9f39-f4067c752287
@CivisIdDefault = 0f8fad5b-d9cb-469f-a165-70867728950e
@LexId = 07a9c194-4f54-4ec0-bcda-d31a5ee4893d


###
# Listar Rogationes: 
GET {{CorpusLegis.API_HostAddress}}/rogatio
Accept: application/json
###

###
# Obtener un solo Rogatio
GET {{CorpusLegis.API_HostAddress}}/rogatio/{{RogatioId}}
Accept: application/json
X-Civis-Id: {{CivisIdDefault}}
###

###
# Crea un Rogatio
POST {{CorpusLegis.API_HostAddress}}/rogatio
Content-type: application/json
X-Civis-Id: {{CivisIdDefault}}

{
  "title": "Amarse",
  "content": "Juntos somos"
}
###

###
# Actualizar un Rogatio
PUT {{CorpusLegis.API_HostAddress}}/rogatio/{{RogatioId}}
Content-type: application/json
X-Civis-Id: {{CivisIdDefault}}

{
  "title": "Se amen",
  "content": "Son juntos"
}
###

###
# Eliminar un Rogatio
DELETE {{CorpusLegis.API_HostAddress}}/rogatio/{{RogatioId}}
###

###
# Transicionar estado de Rogatio
PUT {{CorpusLegis.API_HostAddress}}/rogatio/{{RogatioId}}/status
Content-type: application/json
X-Civis-Id: {{CivisIdDefault}}

{
  "status": 1
}
###

###
# Votar en una Rogatio
POST {{CorpusLegis.API_HostAddress}}/rogatio/{{RogatioId}}/vote
Content-type: application/json
X-Civis-Id: {{CivisIdDefault}}

{
  "rogatioid": "{{RogatioId}}",
  "civisid": "{{CivisIdDefault}}",
  "votum": 0
}
###

###
# Listar Leges: 
GET {{CorpusLegis.API_HostAddress}}/lex
Content-type: application/json
X-Civis-Id: {{CivisIdDefault}}
###

###
# Obtener una sola Lex
GET {{CorpusLegis.API_HostAddress}}/lex/{{LexId}}
Content-type: application/json
X-Civis-Id: {{CivisIdDefault}}
###
