<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CorpusLegis.EscrutinioWorker-2b3e07c2-d14e-47a4-9ec3-341bd1fd53df</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.AccessTokenManagement" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CorpusLegis.ServiceDefaults\CorpusLegis.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
