// <auto-generated />
using System;
using CorpusLegis.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorpusLegis.API.Migrations
{
    [DbContext(typeof(CorpusLegisContext))]
    [Migration("20260224222345_InitialDomain")]
    partial class InitialDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CivisCivitas", b =>
                {
                    b.Property<Guid>("CivesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CivitatesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CivesId", "CivitatesId");

                    b.HasIndex("CivitatesId");

                    b.ToTable("CivisCivitas");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Civis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cives");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Civitas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FoundedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Civitates");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Lex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CivitasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DerogatedByLexId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginRogatioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PromulgatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CivitasId");

                    b.HasIndex("DerogatedByLexId");

                    b.HasIndex("OriginRogatioId");

                    b.ToTable("Leges");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Rogatio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CivisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CivitasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CivisId");

                    b.HasIndex("CivitasId");

                    b.ToTable("Rogationes");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Sententia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CivisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RogatioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CivisId");

                    b.HasIndex("RogatioId");

                    b.ToTable("Sententiae");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Suffragium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CastAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CivisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RogatioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Votum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CivisId");

                    b.HasIndex("RogatioId", "CivisId")
                        .IsUnique();

                    b.ToTable("Suffragia");
                });

            modelBuilder.Entity("CivisCivitas", b =>
                {
                    b.HasOne("CorpusLegis.API.Domain.Civis", null)
                        .WithMany()
                        .HasForeignKey("CivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpusLegis.API.Domain.Civitas", null)
                        .WithMany()
                        .HasForeignKey("CivitatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Lex", b =>
                {
                    b.HasOne("CorpusLegis.API.Domain.Civitas", "Civitas")
                        .WithMany("Leges")
                        .HasForeignKey("CivitasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpusLegis.API.Domain.Lex", "DerogatedByLex")
                        .WithMany()
                        .HasForeignKey("DerogatedByLexId");

                    b.HasOne("CorpusLegis.API.Domain.Rogatio", "OriginRogatio")
                        .WithMany()
                        .HasForeignKey("OriginRogatioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Civitas");

                    b.Navigation("DerogatedByLex");

                    b.Navigation("OriginRogatio");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Rogatio", b =>
                {
                    b.HasOne("CorpusLegis.API.Domain.Civis", "Civis")
                        .WithMany()
                        .HasForeignKey("CivisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpusLegis.API.Domain.Civitas", "Civitas")
                        .WithMany("Rogationes")
                        .HasForeignKey("CivitasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Civis");

                    b.Navigation("Civitas");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Sententia", b =>
                {
                    b.HasOne("CorpusLegis.API.Domain.Civis", "Civis")
                        .WithMany()
                        .HasForeignKey("CivisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpusLegis.API.Domain.Rogatio", "Rogatio")
                        .WithMany("Sententiae")
                        .HasForeignKey("RogatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Civis");

                    b.Navigation("Rogatio");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Suffragium", b =>
                {
                    b.HasOne("CorpusLegis.API.Domain.Civis", "Civis")
                        .WithMany()
                        .HasForeignKey("CivisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpusLegis.API.Domain.Rogatio", "Rogatio")
                        .WithMany("Suffragia")
                        .HasForeignKey("RogatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Civis");

                    b.Navigation("Rogatio");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Civitas", b =>
                {
                    b.Navigation("Leges");

                    b.Navigation("Rogationes");
                });

            modelBuilder.Entity("CorpusLegis.API.Domain.Rogatio", b =>
                {
                    b.Navigation("Sententiae");

                    b.Navigation("Suffragia");
                });
#pragma warning restore 612, 618
        }
    }
}
